language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm run build-storybook
deploy:
  provider: surge
  skip_cleanup: true
  domain: simple-react-components.surge.sh
  project: ./storybook-static
on:
  branch: master
